### ISSUE TITLE
mismatch file format in GQN

### ISSUE THREAD

**Issue by tatsuhiko-inoue** [masa-su/pixyzoo#15]
GQN/dataset/convert2torch.py generate data files compressed by gzip.
But GQNDataset class expect uncompressed files.

The following error occurred when I executed GAN/train.py with the directory generated by convert2torch.py.

```
Traceback (most recent call last):
  File "train.py", line 94, in <module>
    x_data_test, v_data_test = next(iter(test_loader))
  File "/home/hoge/venv/pytorch-py36-cuda9/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 615, in __next__
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "/home/hoge/venv/pytorch-py36-cuda9/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 615, in <listcomp>
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "/home/hoge/work/pixyzoo/GQN/gqn_dataset.py", line 32, in __getitem__
    data = torch.load(scene_path)
  File "/home/hoge/venv/pytorch-py36-cuda9/lib/python3.6/site-packages/torch/serialization.py", line 365, in load
    f = open(f, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'dataset/rooms_ring_camera-torch/train/1414.pt'
```

**Comment by TMats** [comment]
Hi, doesn't the uncompressing command `gzip -d *.gz` help?

**Comment by tatsuhiko-inoue** [comment]
Thank you for your reply!

By uncompressing the dataset files, I was able to run train.py.
But is it okay that the data format does not match?
